### ISSUE TITLE
自动闭合标签修复出错？

### ISSUE THREAD

**Issue by bwqgithub** [virtoolswebplayer/eslint-vue-js-fixer#2]
![qq 20170821142955](https://user-images.githubusercontent.com/11193687/29506244-3e4fc894-867d-11e7-80cf-326081977389.png)
![cuowu](https://user-images.githubusercontent.com/11193687/29506327-a63f1630-867d-11e7-92d6-3be11f0b8edf.png)

我使用的muse框架，在执行fix的时候自动闭合标签会被全部更改为错误的嵌套，能不能设置fix的时候不去修复自动闭合标签

**Comment by virtoolswebplayer** [comment]
嗯，不错的建议。
